"use strict";

const CORPUS_URL = "../corpus/index-v0.1.json";
const CASE_ID = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const ROLES = new Set(["DERIVATION", "EVALUATION"]);
const EVALUATION_MODES = new Set(["SURFACED_TRAP_ADJUDICATION", "LATENT_TRAP_DETECTION"]);
function requireString(value,label){if(typeof value!=="string"||value.trim()==="")throw new Error(`${label} must be a non-empty string`);return value;}
function projectCorpus(corpus){
 if(!corpus||typeof corpus!=="object"||Array.isArray(corpus))throw new Error("corpus root must be an object"); if(!Array.isArray(corpus.cases))throw new Error("corpus.cases must be an array"); if(!corpus.trap_classes||typeof corpus.trap_classes!=="object"||Array.isArray(corpus.trap_classes))throw new Error("corpus.trap_classes must be an object");
 const knownTraps=new Set(Object.keys(corpus.trap_classes)),seenIds=new Set(); const cases=corpus.cases.map((entry,index)=>{const at=`cases[${index}]`,id=requireString(entry?.id,`${at}.id`); if(!CASE_ID.test(id))throw new Error(`${at}.id has unsupported format: ${id}`); if(seenIds.has(id))throw new Error(`duplicate case id: ${id}`); seenIds.add(id); const title=requireString(entry.title,`${at}.title`),domain=requireString(entry.domain,`${at}.domain`),jurisdiction=requireString(entry.jurisdiction,`${at}.jurisdiction`),decisiveTrap=requireString(entry.decisive_trap,`${at}.decisive_trap`); if(!Array.isArray(entry.trap_classes)||entry.trap_classes.length===0)throw new Error(`${at}.trap_classes must be a non-empty array`); const trapClasses=entry.trap_classes.map(t=>{requireString(t,`${at}.trap_classes[]`);if(!knownTraps.has(t))throw new Error(`${at} references unknown trap class: ${t}`);return t;}); const role=entry.provenance?.role;if(!ROLES.has(role))throw new Error(`${at}.provenance.role is unsupported: ${String(role)}`); const issue=entry.provenance?.issue;if(!Number.isInteger(issue)||issue<1)throw new Error(`${at}.provenance.issue must be a positive integer`); let evaluationMode=null;if(entry.evaluation_mode!==undefined){if(!EVALUATION_MODES.has(entry.evaluation_mode))throw new Error(`${at}.evaluation_mode is unsupported: ${String(entry.evaluation_mode)}`);evaluationMode=entry.evaluation_mode;} if(entry.evaluation_result!==undefined&&role!=="EVALUATION")throw new Error(`${at}.evaluation_result is only supported for EVALUATION cases`);if(evaluationMode!==null&&role!=="EVALUATION")throw new Error(`${at}.evaluation_mode is only supported for EVALUATION cases`); const exposure=entry.exposure;if(!exposure||typeof exposure!=="object")throw new Error(`${at}.exposure must be an object`); const exposureStatus=requireString(exposure.status,`${at}.exposure.status`),futureUse=requireString(exposure.future_use,`${at}.exposure.future_use`);if(typeof exposure.blind_reuse!=="boolean")throw new Error(`${at}.exposure.blind_reuse must be boolean`); if(!Array.isArray(entry.evidence_refs)||entry.evidence_refs.length===0)throw new Error(`${at}.evidence_refs must be a non-empty array`);const evidenceRefs=entry.evidence_refs.map(r=>{requireString(r,`${at}.evidence_refs[]`);if(!/^issue:\d+$/.test(r)&&!/^path:[^/].*/.test(r))throw new Error(`${at} has unsupported evidence ref: ${r}`);return r;}); return Object.freeze({id,title,domain,jurisdiction,decisiveTrap,trapClasses:Object.freeze([...trapClasses]),role,issue,evaluationMode,evaluationResult:entry.evaluation_result??null,exposureStatus,blindReuse:exposure.blind_reuse,futureUse,evidenceRefs:Object.freeze([...evidenceRefs])});});
 const roleCounts={DERIVATION:0,EVALUATION:0},modeCounts={SURFACED_TRAP_ADJUDICATION:0,LATENT_TRAP_DETECTION:0,UNSPECIFIED:0};for(const e of cases){roleCounts[e.role]++;if(e.role==="EVALUATION")modeCounts[e.evaluationMode??"UNSPECIFIED"]++;} return Object.freeze({cases:Object.freeze(cases),summary:Object.freeze({totalCases:cases.length,trapClasses:knownTraps.size,roleCounts:Object.freeze(roleCounts),modeCounts:Object.freeze(modeCounts)})});
}
function filterCases(cases,filters={}){const query=String(filters.query??"").trim().toLocaleLowerCase();return cases.filter(e=>{const haystack=[e.title,e.domain,e.jurisdiction,e.decisiveTrap].join(" ").toLocaleLowerCase();return(!query||haystack.includes(query))&&(!filters.trap||e.trapClasses.includes(filters.trap))&&(!filters.domain||e.domain===filters.domain)&&(!filters.jurisdiction||e.jurisdiction===filters.jurisdiction)&&(!filters.role||e.role===filters.role)&&(!filters.evaluationMode||(e.evaluationMode??"UNSPECIFIED")===filters.evaluationMode);});}
function filterOptions(cases){const unique=v=>[...new Set(v)].sort((a,b)=>a.localeCompare(b));return{traps:unique(cases.flatMap(e=>e.trapClasses)),domains:unique(cases.map(e=>e.domain)),jurisdictions:unique(cases.map(e=>e.jurisdiction)),roles:unique(cases.map(e=>e.role)),evaluationModes:unique(cases.filter(e=>e.role==="EVALUATION").map(e=>e.evaluationMode??"UNSPECIFIED"))};}
function caseFromHash(cases,hash){if(!hash)return null;const match=/^#case\/([a-z0-9-]+)$/.exec(hash);if(!match)return undefined;return cases.find(e=>e.id===match[1]);}
function relatedByTrap(cases,selected){return cases.filter(e=>e.id!==selected.id&&e.trapClasses.some(t=>selected.trapClasses.includes(t)));}
function renderSummary(summary,root){const values={"summary-total":summary.totalCases,"summary-traps":summary.trapClasses,"summary-derivation":summary.roleCounts.DERIVATION,"summary-evaluation":summary.roleCounts.EVALUATION,"summary-surfaced":summary.modeCounts.SURFACED_TRAP_ADJUDICATION,"summary-latent":summary.modeCounts.LATENT_TRAP_DETECTION,"summary-unspecified":summary.modeCounts.UNSPECIFIED};for(const[id,value]of Object.entries(values))root.querySelector(`#${id}`).textContent=String(value);}
function populateSelect(select,values){for(const value of values){const option=document.createElement("option");option.value=value;option.textContent=value.replaceAll("_"," ");select.append(option);}}
function renderCases(cases,list,count,empty){list.replaceChildren();count.textContent=`${cases.length} ${cases.length===1?"case":"cases"}`;empty.hidden=cases.length!==0;for(const entry of cases){const item=document.createElement("li"),link=document.createElement("a"),heading=document.createElement("h3"),meta=document.createElement("p"),trap=document.createElement("p");link.href=`#case/${entry.id}`;link.textContent=entry.title;heading.append(link);meta.textContent=`${entry.domain} · ${entry.jurisdiction} · ${entry.role}`;trap.textContent=entry.decisiveTrap;item.append(heading,meta,trap);list.append(item);}}
function evidenceLink(ref){const a=document.createElement("a");if(ref.startsWith("issue:")){const n=ref.slice(6);a.href=`https://github.com/kaastumor/morrow-needle/issues/${n}`;a.textContent=`Issue #${n}`;}else{const p=ref.slice(5);a.href=`../${p}`;a.textContent=p;}return a;}
function renderDetail(cases,detail,selected){detail.replaceChildren();detail.hidden=false;if(selected===undefined){const h=document.createElement("h2");h.textContent="Case not found";const p=document.createElement("p");p.textContent="This case ID is invalid or no longer exists in the canonical corpus.";const back=document.createElement("a");back.href="#";back.textContent="Back to cases";detail.append(h,p,back);return;} if(selected===null){detail.hidden=true;return;} const back=document.createElement("a");back.href="#";back.textContent="← Back to cases";const h=document.createElement("h2");h.textContent=selected.title;const dl=document.createElement("dl");const rows=[["Domain",selected.domain],["Jurisdiction",selected.jurisdiction],["Decisive trap",selected.decisiveTrap],["Trap classes",selected.trapClasses.join(", ")],["Provenance",`Issue #${selected.issue} · ${selected.role}`],["Exposure",`${selected.exposureStatus} · blind reuse: ${selected.blindReuse} · ${selected.futureUse}`]];if(selected.evaluationMode)rows.push(["Evaluation mode",selected.evaluationMode]);if(selected.evaluationResult)rows.push(["Evaluation result",selected.evaluationResult]);for(const[label,value]of rows){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=label;dd.textContent=String(value);dl.append(dt,dd);} const eh=document.createElement("h3");eh.textContent="Evidence";const refs=document.createElement("ul");for(const ref of selected.evidenceRefs){const li=document.createElement("li");li.append(evidenceLink(ref));refs.append(li);} detail.append(back,h,dl,eh,refs);const related=relatedByTrap(cases,selected);if(related.length){const rh=document.createElement("h3");rh.textContent="Related by trap class";const ul=document.createElement("ul");for(const e of related){const li=document.createElement("li"),a=document.createElement("a");a.href=`#case/${e.id}`;a.textContent=e.title;li.append(a);ul.append(li);}detail.append(rh,ul);}}
function wireBrowser(projection){const form=document.querySelector("#case-filters"),list=document.querySelector("#case-list"),count=document.querySelector("#result-count"),empty=document.querySelector("#empty-results"),detail=document.querySelector("#case-detail"),browse=document.querySelector("#browse-panel");const options=filterOptions(projection.cases);populateSelect(form.elements.trap,options.traps);populateSelect(form.elements.domain,options.domains);populateSelect(form.elements.jurisdiction,options.jurisdictions);populateSelect(form.elements.role,options.roles);populateSelect(form.elements.evaluationMode,options.evaluationModes);const apply=()=>{const filters=Object.fromEntries(new FormData(form).entries());renderCases(filterCases(projection.cases,filters),list,count,empty);};const route=()=>{const selected=caseFromHash(projection.cases,location.hash);browse.hidden=selected!==null;renderDetail(projection.cases,detail,selected);if(selected!==null)detail.querySelector("a")?.focus();};form.addEventListener("input",apply);form.addEventListener("reset",()=>setTimeout(apply,0));window.addEventListener("hashchange",route);apply();route();}
async function loadCorpus(){const status=document.querySelector("#corpus-status"),root=document.querySelector("#corpus-root");try{const response=await fetch(CORPUS_URL,{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const projection=projectCorpus(await response.json());renderSummary(projection.summary,root);wireBrowser(projection);status.textContent=`Canonical corpus validated: ${projection.summary.totalCases} cases.`;root.dataset.loaded="true";root.hidden=false;}catch(error){status.setAttribute("role","alert");status.textContent=`Corpus unavailable or invalid (${error.message}). Nothing was rendered.`;root.hidden=true;}}
if(typeof module!=="undefined"&&module.exports)module.exports={projectCorpus,filterCases,filterOptions,caseFromHash,relatedByTrap};if(typeof document!=="undefined")loadCorpus();
