"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");const{projectCorpus,filterCases,filterOptions,caseFromHash,relatedByTrap}=require("./app.js");
function caseRecord(overrides={}){return{id:"safe-case",title:"Safe case",domain:"test",jurisdiction:"EU",trap_classes:["TRAP"],provenance:{issue:1,role:"DERIVATION"},exposure:{status:"PUBLIC_FROM_DISCOVERY",blind_reuse:false,future_use:"REGRESSION_ONLY"},decisive_trap:"A concrete trap.",evidence_refs:["issue:1","path:fixtures/example.json"],...overrides};}function corpus(cases){return{trap_classes:{TRAP:"Trap description",OTHER:"Other"},cases};}
test("projects every current canonical corpus case",()=>{const file=path.join(__dirname,"..","corpus","index-v0.1.json"),input=JSON.parse(fs.readFileSync(file,"utf8")),projection=projectCorpus(input);assert.equal(projection.summary.totalCases,input.cases.length);assert.equal(projection.summary.trapClasses,Object.keys(input.trap_classes).length);assert.equal(projection.summary.roleCounts.DERIVATION+projection.summary.roleCounts.EVALUATION,input.cases.length);for(const entry of projection.cases){assert.ok(entry.issue>0);assert.ok(entry.exposureStatus);assert.ok(entry.evidenceRefs.length>0);}});
test("projects detail metadata without mutating canonical input",()=>{const input=corpus([caseRecord(),caseRecord({id:"evaluation-case",provenance:{issue:2,role:"EVALUATION"},evaluation_mode:"LATENT_TRAP_DETECTION",evaluation_result:"R_PASS_M_PASS"})]),before=JSON.stringify(input),projection=projectCorpus(input);assert.equal(JSON.stringify(input),before);assert.equal(projection.cases[0].futureUse,"REGRESSION_ONLY");assert.equal(projection.cases[1].evaluationResult,"R_PASS_M_PASS");});
test("fails closed when cases array is missing",()=>assert.throws(()=>projectCorpus({trap_classes:{}}),/cases must be an array/));
test("fails closed on malformed IDs, evidence refs and detail ownership",()=>{assert.throws(()=>projectCorpus(corpus([caseRecord({id:"Bad ID"})])),/unsupported format/);assert.throws(()=>projectCorpus(corpus([caseRecord(),caseRecord()])),/duplicate case id/);assert.throws(()=>projectCorpus(corpus([caseRecord({evidence_refs:["https://example.com"]})])),/unsupported evidence ref/);assert.throws(()=>projectCorpus(corpus([caseRecord({provenance:{issue:0,role:"DERIVATION"}})])),/positive integer/);assert.throws(()=>projectCorpus(corpus([caseRecord({exposure:{status:"X",blind_reuse:"no",future_use:"Y"}})])),/blind_reuse must be boolean/);});
test("fails closed on unknown trap and unsupported evaluation metadata",()=>{assert.throws(()=>projectCorpus(corpus([caseRecord({trap_classes:["UNKNOWN"]})])),/unknown trap class/);assert.throws(()=>projectCorpus(corpus([caseRecord({provenance:{issue:2,role:"EVALUATION"},evaluation_mode:"MAGIC"})])),/evaluation_mode is unsupported/);assert.throws(()=>projectCorpus(corpus([caseRecord({evaluation_result:"PASS"})])),/only supported for EVALUATION/);});
test("search and filters remain deterministic",()=>{const cases=projectCorpus(corpus([caseRecord({title:"Alpha",domain:"Competition",jurisdiction:"EU",decisive_trap:"Hidden Clock",trap_classes:["TRAP","OTHER"]}),caseRecord({id:"eval-case",title:"Beta",domain:"Safety",jurisdiction:"NL",decisive_trap:"Other issue",trap_classes:["OTHER"],provenance:{issue:2,role:"EVALUATION"},evaluation_mode:"LATENT_TRAP_DETECTION"})])).cases;assert.deepEqual(filterCases(cases,{query:"clock"}).map(e=>e.id),["safe-case"]);assert.deepEqual(filterCases(cases,{trap:"OTHER",role:"EVALUATION"}).map(e=>e.id),["eval-case"]);assert.deepEqual(filterOptions(cases).roles,["DERIVATION","EVALUATION"]);});
test("deep links resolve stable IDs and fail visibly for invalid or deleted IDs",()=>{const cases=projectCorpus(corpus([caseRecord()])).cases;assert.equal(caseFromHash(cases,"#case/safe-case").id,"safe-case");assert.equal(caseFromHash(cases,"#case/deleted-case"),undefined);assert.equal(caseFromHash(cases,"#nonsense"),undefined);assert.equal(caseFromHash(cases,""),null);});
test("related navigation derives only from shared trap membership",()=>{const cases=projectCorpus(corpus([caseRecord({trap_classes:["TRAP"]}),caseRecord({id:"shared-case",trap_classes:["TRAP","OTHER"]}),caseRecord({id:"other-case",trap_classes:["OTHER"]})])).cases;assert.deepEqual(relatedByTrap(cases,cases[0]).map(e=>e.id),["shared-case"]);});
test("MVP explains protocol and exposed-case boundary without marketing claims",()=>{const html=fs.readFileSync(path.join(__dirname,"index.html"),"utf8");for(const term of["DERIVATION","EVALUATION","SURFACED_TRAP_ADJUDICATION","LATENT_TRAP_DETECTION","must not be treated as fresh blind evidence"])assert.match(html,new RegExp(term));assert.doesNotMatch(html,/best|superior|accurate legal advice/i);});
test("static accessibility and narrow-screen baseline is present",()=>{const html=fs.readFileSync(path.join(__dirname,"index.html"),"utf8"),css=fs.readFileSync(path.join(__dirname,"styles.css"),"utf8");assert.match(html,/class="skip-link" href="#explorer"/);assert.match(html,/aria-label="Case filters"/);assert.match(css,/:focus-visible/);assert.match(css,/@media \(max-width: 36rem\)/);assert.match(css,/\.case-detail dl \{ grid-template-columns: 1fr/);});
